"""Core modules: CMC fabric, energy, voting, attractors, homeostasis.

CMC (Canonical Microcircuits): L4 → L5/6 → L2/3 column dynamics.
Voting: k-WTA lateral inhibition for column consensus.
Attractors: multistable dynamics for task selection via short-term plasticity.
Homeostasis: interoceptive setpoints and deviation (S4).
Actuation: open option window over tools for goal selection (S8); facts and
conditions (guard/regularity) for "default + enrichment" (S8 stage 2); effects
and irreversibility-as-stance (S8 stage 3); reactive Behavior Tree (S8 stage 4).
Functional Core / Imperative Shell (ADR-0004) across all core/* modules.
"""

from .actuation import (
    DEFAULT_FACT_VALUE,
    FACTS,
    NETWORK_AVAILABLE,
    TOPIC_BOUND,
    Actuation,
    ActuationKind,
    ActuationPreferences,
    ActuationResult,
    ActuationStatus,
    Effect,
    Fact,
    Guard,
    Node,
    NodeKind,
    NodeStatus,
    Option,
    OptionCandidate,
    OptionContext,
    OptionSource,
    OptionTrace,
    OptionWindow,
    Regularity,
    TickContext,
    TickMemory,
    ToolAnnotations,
    build_options,
    classify_reversible,
    evaluate_fact,
    guard_holds,
    order_children,
    regularity_cost,
    score_option,
    select_option,
    tick,
)
from .attractors import (
    TaskAttraction,
    TaskAttractor,
    check_basin_stability,
    check_immediate_switch,
    compute_dwell,
)
from .cmc import CMCEnsemble, ColumnConfig, ColumnState, EnsembleOutput, column_step
from .homeostasis import (
    HomeostasisState,
    Homeostat,
    HomeostaticSignal,
    Setpoint,
    setpoint_deviation,
)
from .policy import (
    Action,
    MacroContext,
    PolicyCandidate,
    PolicyContext,
    PolicyTrace,
    Preferences,
    evaluate_candidates,
    select_action,
)
from .voting import VotingManager, VotingResult, kwta

__all__ = [
    "DEFAULT_FACT_VALUE",
    "FACTS",
    "NETWORK_AVAILABLE",
    "TOPIC_BOUND",
    "Action",
    "Actuation",
    "ActuationKind",
    "ActuationPreferences",
    "ActuationResult",
    "ActuationStatus",
    "CMCEnsemble",
    "ColumnConfig",
    "ColumnState",
    "Effect",
    "EnsembleOutput",
    "Fact",
    "Guard",
    "HomeostasisState",
    "Homeostat",
    "HomeostaticSignal",
    "MacroContext",
    "Node",
    "NodeKind",
    "NodeStatus",
    "Option",
    "OptionCandidate",
    "OptionContext",
    "OptionSource",
    "OptionTrace",
    "OptionWindow",
    "PolicyCandidate",
    "PolicyContext",
    "PolicyTrace",
    "Preferences",
    "Regularity",
    "Setpoint",
    "TaskAttraction",
    "TaskAttractor",
    "TickContext",
    "TickMemory",
    "ToolAnnotations",
    "VotingManager",
    "VotingResult",
    "build_options",
    "check_basin_stability",
    "check_immediate_switch",
    "classify_reversible",
    "column_step",
    "compute_dwell",
    "evaluate_candidates",
    "evaluate_fact",
    "guard_holds",
    "kwta",
    "order_children",
    "regularity_cost",
    "score_option",
    "select_action",
    "select_option",
    "setpoint_deviation",
    "tick",
]
